version: "3.9"
networks:
  default:
    name: rp

services:
  postgres-1:
    container_name: postgres-1
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gxg
      POSTGRES_USER: "sunny"
      POSTGRES_PASSWORD: "1"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
